version: '3.9'
services:

  app:
    container_name: loja
    build:
      context: .
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USER: ${DATABASE_USER}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
    depends_on:
      - postgres
    ports:
      - "8082:8080"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: controle
    ports:
      - "5432:5432"
    volumes:
      - loja_volume:/var/lib/postgresql/data/

volumes:
  loja_volume: