

spring:
  application:
    name: demo-cliente
  jpa:
    hibernate:
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.community.dialect.FirebirdDialect
  datasource:
    url: jdbc:firebirdsql:localhost/3050:controle.db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: sysdba
    password: rootvanity


