create table cliente
(
    id                 bigint generated by default as identity
        primary key,
    created_at         timestamp,
    updated_at         timestamp,
    bairro             varchar(80),
    cep                varchar(8),
    cnae               varchar(255),
    cnpj               varchar(14)
        constraint uk_2vf89ija5fea0souakqh3bg59
            unique,
    complemento        varchar(20),
    inicio_atividade   date,
    inscricao_estadual varchar(10),
    logradouro         varchar(150),
    municipio          varchar(80),
    numero             varchar(7),
    razao_social       varchar(255),
    telefone           varchar(15),
    uf                 varchar(2)
);

alter table cliente
    owner to root;

