create table agendamento
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp,
    updated_at     timestamp,
    data_pagamento date             not null,
    fornecedor     varchar(100)     not null,
    pago           boolean,
    valor          double precision not null
);


alter table agendamento
    owner to root;

