create table pagamento
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp,
    updated_at     timestamp,
    data_pagamento date,
    pag_descricao  varchar(150),
    tipo           varchar(15)      not null,
    valor          double precision not null,
    compra_id      bigint
        constraint pagamento_compra_fk
            references compra
);

alter table pagamento
    owner to root;

