create table produto
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp,
    updated_at timestamp,
    descricao  varchar(150),
    preco      double precision not null,
    quantidade integer          not null,
    compra_id  bigint
        constraint produto_compra_fk
            references compra
);

alter table produto
    owner to root;

